#!/usr/bin/env python3
"""
build_standards_catalog.py — Buduje katalog wymaganych dokumentów dla 44 standardów.

Dla każdego standardu definiuje listę typów dokumentów które standard
wymaga (is_required=True) lub zaleca (is_required=False).
Źródła: oficjalne specyfikacje, iso.org scope, Wikipedia, publiczne TOC.

Wynik: tabela standards_catalog w DB.
"""

from __future__ import annotations

import argparse
import sqlite3
from pathlib import Path

DB_DEFAULT = Path(__file__).parent.parent / "reports" / "it_doc_matrix.db"

# ---------------------------------------------------------------------------
# Canonical catalog — knowledge base
# Każdy standard → lista dokumentów: (doc_type_id, doc_title, is_required, category, source_url, notes)
# is_required: True = standard WYMAGA, False = standard ZALECA
# ---------------------------------------------------------------------------

CATALOG: dict[str, list[tuple]] = {
    # ── IEEE 829 — dokumentacja testowania ──────────────────────────────────
    "IEEE 829": [
        (
            "ieee829_test_plan",
            "Test Plan",
            True,
            "testing",
            "https://standards.ieee.org/ieee/829/776/",
            "Główny plan testowania: zakres, podejście, zasoby, harmonogram",
        ),
        (
            "ieee829_test_design",
            "Test Design Specification",
            True,
            "testing",
            "https://standards.ieee.org/ieee/829/776/",
            "Specyfikacja cech do przetestowania i metody",
        ),
        (
            "ieee829_test_case",
            "Test Case Specification",
            True,
            "testing",
            "https://standards.ieee.org/ieee/829/776/",
            "Szczegółowe warunki i dane wejściowe dla testu",
        ),
        (
            "ieee829_test_procedure",
            "Test Procedure Specification",
            True,
            "testing",
            "https://standards.ieee.org/ieee/829/776/",
            "Kroki wykonania testów",
        ),
        (
            "ieee829_test_log",
            "Test Log",
            True,
            "testing",
            "https://standards.ieee.org/ieee/829/776/",
            "Chronologiczny zapis przebiegu testów",
        ),
        (
            "ieee829_test_incident",
            "Test Incident Report",
            True,
            "testing",
            "https://standards.ieee.org/ieee/829/776/",
            "Raport zdarzeń wymagających inspekcji",
        ),
        (
            "ieee829_test_summary",
            "Test Summary Report",
            True,
            "testing",
            "https://standards.ieee.org/ieee/829/776/",
            "Podsumowanie: ocena testowania vs kryteria",
        ),
        (
            "ieee829_transmittal",
            "Test Item Transmittal Report",
            False,
            "testing",
            "https://standards.ieee.org/ieee/829/776/",
            "Raport przekazania elementów do testowania",
        ),
    ],
    # ── IEEE 830 — SRS ────────────────────────────────────────────────────
    "IEEE 830": [
        (
            "ieee830_srs",
            "Software Requirements Specification",
            True,
            "requirements",
            "https://standards.ieee.org/ieee/830/1191/",
            "Kompletna specyfikacja wymagań oprogramowania",
        ),
        (
            "ieee830_srs_prototype",
            "Requirements Prototype",
            False,
            "requirements",
            "https://standards.ieee.org/ieee/830/1191/",
            "Prototyp do wyjaśnienia niejasnych wymagań",
        ),
    ],
    # ── IEEE 1012 — weryfikacja i walidacja ───────────────────────────────
    "IEEE 1012": [
        (
            "ieee1012_vv_plan",
            "Software V&V Plan",
            True,
            "testing",
            "https://standards.ieee.org/ieee/1012/5609/",
            "Plan weryfikacji i walidacji (IV&V lub IV&V)",
        ),
        (
            "ieee1012_vv_report",
            "Software V&V Report",
            True,
            "testing",
            "https://standards.ieee.org/ieee/1012/5609/",
            "Raport wyników V&V per faza",
        ),
        (
            "ieee1012_anomaly_report",
            "Anomaly Report",
            True,
            "testing",
            "https://standards.ieee.org/ieee/1012/5609/",
            "Raport anomalii wykrytych podczas V&V",
        ),
        (
            "ieee1012_task_report",
            "V&V Task Report",
            True,
            "testing",
            "https://standards.ieee.org/ieee/1012/5609/",
            "Raport zadania V&V (per aktywność)",
        ),
    ],
    # ── IEEE 1016 — opis projektowania ────────────────────────────────────
    "IEEE 1016": [
        (
            "ieee1016_sdd",
            "Software Design Description (SDD)",
            True,
            "design",
            "https://standards.ieee.org/ieee/1016/4502/",
            "Pełny opis projektu oprogramowania — konteksty, architektura, dekompozycja",
        ),
        (
            "ieee1016_design_rationale",
            "Design Rationale",
            False,
            "design",
            "https://standards.ieee.org/ieee/1016/4502/",
            "Uzasadnienie decyzji projektowych",
        ),
    ],
    # ── IEEE 42010 — opis architektoniczny ────────────────────────────────
    "IEEE 42010": [
        (
            "ieee42010_arch_description",
            "Architecture Description",
            True,
            "architecture",
            "https://standards.ieee.org/ieee/42010/6205/",
            "Formalny opis architektury systemu wg. viewpoints",
        ),
        (
            "ieee42010_arch_viewpoint",
            "Architecture Viewpoint",
            True,
            "architecture",
            "https://standards.ieee.org/ieee/42010/6205/",
            "Perspektywa architektoniczna (np. deployment, logical)",
        ),
        (
            "ieee42010_arch_decision",
            "Architecture Decision Record (ADR)",
            False,
            "architecture",
            "https://standards.ieee.org/ieee/42010/6205/",
            "Zapis decyzji architektonicznej",
        ),
        (
            "ieee42010_arch_rationale",
            "Architecture Rationale",
            False,
            "architecture",
            "https://standards.ieee.org/ieee/42010/6205/",
            "Uzasadnienie decyzji architektonicznych",
        ),
    ],
    # ── ISO/IEC 12207 — cykl życia oprogramowania ─────────────────────────
    "ISO/IEC 12207": [
        (
            "iso12207_software_req_spec",
            "Software Requirements Specification",
            True,
            "requirements",
            "https://www.iso.org/standard/63712.html",
            "Wymagania systemowe oprogramowania",
        ),
        (
            "iso12207_software_arch",
            "Software Architecture Description",
            True,
            "architecture",
            "https://www.iso.org/standard/63712.html",
            "Architektura komponentów i interfejsów",
        ),
        (
            "iso12207_detailed_design",
            "Software Detailed Design",
            True,
            "design",
            "https://www.iso.org/standard/63712.html",
            "Szczegółowy projekt modułów",
        ),
        (
            "iso12207_test_plan",
            "Software Test Plan",
            True,
            "testing",
            "https://www.iso.org/standard/63712.html",
            "Plan testowania oprogramowania",
        ),
        (
            "iso12207_test_report",
            "Software Test Report",
            True,
            "testing",
            "https://www.iso.org/standard/63712.html",
            "Raport wyników testów",
        ),
        (
            "iso12207_config_mgmt_plan",
            "Configuration Management Plan",
            True,
            "process",
            "https://www.iso.org/standard/63712.html",
            "Plan zarządzania konfiguracją",
        ),
        (
            "iso12207_qa_plan",
            "Software Quality Assurance Plan",
            True,
            "quality",
            "https://www.iso.org/standard/63712.html",
            "Plan zapewnienia jakości oprogramowania",
        ),
        (
            "iso12207_review_record",
            "Software Review Record",
            True,
            "process",
            "https://www.iso.org/standard/63712.html",
            "Protokół przeglądu",
        ),
        (
            "iso12207_change_request",
            "Change Request",
            True,
            "process",
            "https://www.iso.org/standard/63712.html",
            "Wniosek o zmianę",
        ),
        (
            "iso12207_problem_report",
            "Problem Report",
            True,
            "process",
            "https://www.iso.org/standard/63712.html",
            "Raport problemu/defektu",
        ),
        (
            "iso12207_maintenance_plan",
            "Software Maintenance Plan",
            False,
            "process",
            "https://www.iso.org/standard/63712.html",
            "Plan konserwacji i wsparcia",
        ),
        (
            "iso12207_user_docs",
            "User Documentation",
            True,
            "documentation",
            "https://www.iso.org/standard/63712.html",
            "Dokumentacja użytkownika końcowego",
        ),
        (
            "iso12207_deployment_plan",
            "Deployment/Installation Plan",
            False,
            "operations",
            "https://www.iso.org/standard/63712.html",
            "Plan wdrożenia/instalacji",
        ),
    ],
    # ── ISO/IEC 15288 — cykl życia systemów ───────────────────────────────
    "ISO/IEC 15288": [
        (
            "iso15288_conops",
            "Concept of Operations (ConOps)",
            True,
            "requirements",
            "https://www.iso.org/standard/63711.html",
            "Koncepcja działania systemu",
        ),
        (
            "iso15288_sys_req_spec",
            "System Requirements Specification",
            True,
            "requirements",
            "https://www.iso.org/standard/63711.html",
            "Wymagania systemu",
        ),
        (
            "iso15288_sys_arch",
            "System Architecture Description",
            True,
            "architecture",
            "https://www.iso.org/standard/63711.html",
            "Architektura systemu — elementy i interfejsy",
        ),
        (
            "iso15288_integration_plan",
            "System Integration Plan",
            True,
            "testing",
            "https://www.iso.org/standard/63711.html",
            "Plan integracji podsystemów",
        ),
        (
            "iso15288_verification_plan",
            "System Verification Plan",
            True,
            "testing",
            "https://www.iso.org/standard/63711.html",
            "Plan weryfikacji wymagań systemowych",
        ),
        (
            "iso15288_validation_plan",
            "System Validation Plan",
            True,
            "testing",
            "https://www.iso.org/standard/63711.html",
            "Plan walidacji systemu w środowisku docelowym",
        ),
        (
            "iso15288_maintenance_plan",
            "System Maintenance Plan",
            False,
            "operations",
            "https://www.iso.org/standard/63711.html",
            "Plan konserwacji systemu",
        ),
        (
            "iso15288_disposal_plan",
            "System Disposal Plan",
            False,
            "operations",
            "https://www.iso.org/standard/63711.html",
            "Plan wycofania systemu z eksploatacji",
        ),
    ],
    # ── ISO 9001 — zarządzanie jakością ───────────────────────────────────
    "ISO 9001": [
        (
            "iso9001_quality_manual",
            "Quality Manual",
            True,
            "quality",
            "https://www.iso.org/standard/62085.html",
            "Podręcznik systemu zarządzania jakością (opcjonalny ale praktycznie wymagany)",
        ),
        (
            "iso9001_quality_policy",
            "Quality Policy",
            True,
            "quality",
            "https://www.iso.org/standard/62085.html",
            "Polityka jakości organizacji (Art. 5.2)",
        ),
        (
            "iso9001_quality_objectives",
            "Quality Objectives",
            True,
            "quality",
            "https://www.iso.org/standard/62085.html",
            "Cele jakości (Art. 6.2)",
        ),
        (
            "iso9001_process_map",
            "Process Map / Process Description",
            True,
            "quality",
            "https://www.iso.org/standard/62085.html",
            "Mapa procesów QMS",
        ),
        (
            "iso9001_documented_info",
            "Documented Information (Procedures)",
            True,
            "quality",
            "https://www.iso.org/standard/62085.html",
            "Udokumentowane procedury (Art. 7.5)",
        ),
        (
            "iso9001_risk_register",
            "Risk and Opportunities Register",
            True,
            "quality",
            "https://www.iso.org/standard/62085.html",
            "Rejestr ryzyk i szans (Art. 6.1)",
        ),
        (
            "iso9001_corrective_action",
            "Corrective Action Report",
            True,
            "quality",
            "https://www.iso.org/standard/62085.html",
            "Raport działania korygującego (Art. 10.2)",
        ),
        (
            "iso9001_internal_audit",
            "Internal Audit Report",
            True,
            "quality",
            "https://www.iso.org/standard/62085.html",
            "Raport audytu wewnętrznego (Art. 9.2)",
        ),
        (
            "iso9001_mgmt_review",
            "Management Review Minutes",
            True,
            "quality",
            "https://www.iso.org/standard/62085.html",
            "Protokół przeglądu zarządzania (Art. 9.3)",
        ),
        (
            "iso9001_customer_feedback",
            "Customer Feedback / Satisfaction",
            False,
            "quality",
            "https://www.iso.org/standard/62085.html",
            "Badanie satysfakcji klienta",
        ),
    ],
    # ── ISO 20000-1 — zarządzanie usługami IT ─────────────────────────────
    "ISO 20000-1": [
        (
            "iso20000_smp",
            "Service Management Plan (SMP)",
            True,
            "itsm",
            "https://www.iso.org/standard/70636.html",
            "Plan systemu zarządzania usługami",
        ),
        (
            "iso20000_service_catalog",
            "Service Catalog",
            True,
            "itsm",
            "https://www.iso.org/standard/70636.html",
            "Katalog usług IT",
        ),
        (
            "iso20000_sla",
            "Service Level Agreement (SLA)",
            True,
            "itsm",
            "https://www.iso.org/standard/70636.html",
            "Umowa o poziomie usług",
        ),
        (
            "iso20000_incident_record",
            "Incident Record",
            True,
            "itsm",
            "https://www.iso.org/standard/70636.html",
            "Rekord incydentu usługowego",
        ),
        (
            "iso20000_problem_record",
            "Problem Record",
            True,
            "itsm",
            "https://www.iso.org/standard/70636.html",
            "Rekord problemu",
        ),
        (
            "iso20000_change_request",
            "Change Request",
            True,
            "itsm",
            "https://www.iso.org/standard/70636.html",
            "Wniosek o zmianę",
        ),
        (
            "iso20000_change_schedule",
            "Change Schedule",
            True,
            "itsm",
            "https://www.iso.org/standard/70636.html",
            "Harmonogram zmian",
        ),
        (
            "iso20000_capacity_plan",
            "Capacity and Performance Plan",
            False,
            "itsm",
            "https://www.iso.org/standard/70636.html",
            "Plan pojemności i wydajności",
        ),
        (
            "iso20000_availability_plan",
            "Availability Plan",
            False,
            "itsm",
            "https://www.iso.org/standard/70636.html",
            "Plan dostępności usług",
        ),
        (
            "iso20000_continuity_plan",
            "IT Service Continuity Plan",
            True,
            "itsm",
            "https://www.iso.org/standard/70636.html",
            "Plan ciągłości usług IT",
        ),
    ],
    # ── ISO 22301 — ciągłość działania ────────────────────────────────────
    "ISO 22301": [
        (
            "iso22301_bcms_policy",
            "BCMS Policy",
            True,
            "continuity",
            "https://www.iso.org/standard/75106.html",
            "Polityka systemu zarządzania ciągłością działania",
        ),
        (
            "iso22301_bia",
            "Business Impact Analysis (BIA)",
            True,
            "continuity",
            "https://www.iso.org/standard/75106.html",
            "Analiza wpływu na działalność",
        ),
        (
            "iso22301_risk_assessment",
            "Risk Assessment (BCMS)",
            True,
            "continuity",
            "https://www.iso.org/standard/75106.html",
            "Ocena ryzyka dla ciągłości działania",
        ),
        (
            "iso22301_bcp",
            "Business Continuity Plan (BCP)",
            True,
            "continuity",
            "https://www.iso.org/standard/75106.html",
            "Plan ciągłości działania",
        ),
        (
            "iso22301_dr_plan",
            "Disaster Recovery Plan (DRP)",
            True,
            "continuity",
            "https://www.iso.org/standard/75106.html",
            "Plan odtwarzania po awarii",
        ),
        (
            "iso22301_crisis_comms",
            "Crisis Communication Plan",
            True,
            "continuity",
            "https://www.iso.org/standard/75106.html",
            "Plan komunikacji kryzysowej",
        ),
        (
            "iso22301_exercise_report",
            "Exercise and Testing Report",
            True,
            "continuity",
            "https://www.iso.org/standard/75106.html",
            "Raport z ćwiczeń i testów ciągłości",
        ),
        (
            "iso22301_internal_audit",
            "BCMS Internal Audit Report",
            True,
            "continuity",
            "https://www.iso.org/standard/75106.html",
            "Raport audytu wewnętrznego BCMS",
        ),
    ],
    # ── ISO/IEC 27001 — ISMS ──────────────────────────────────────────────
    "ISO/IEC 27001": [
        (
            "iso27001_isms_scope",
            "ISMS Scope Statement",
            True,
            "security",
            "https://www.iso.org/standard/27001",
            "Zakres ISMS (Art. 4.3)",
        ),
        (
            "iso27001_risk_assessment",
            "Information Security Risk Assessment",
            True,
            "security",
            "https://www.iso.org/standard/27001",
            "Ocena ryzyka bezpieczeństwa informacji (Art. 6.1)",
        ),
        (
            "iso27001_risk_treatment",
            "Risk Treatment Plan",
            True,
            "security",
            "https://www.iso.org/standard/27001",
            "Plan postępowania z ryzykiem",
        ),
        (
            "iso27001_soa",
            "Statement of Applicability (SoA)",
            True,
            "security",
            "https://www.iso.org/standard/27001",
            "Deklaracja stosowalności zabezpieczeń Annex A",
        ),
        (
            "iso27001_isms_policy",
            "Information Security Policy",
            True,
            "security",
            "https://www.iso.org/standard/27001",
            "Polityka bezpieczeństwa informacji",
        ),
        (
            "iso27001_asset_inventory",
            "Information Asset Inventory",
            True,
            "security",
            "https://www.iso.org/standard/27001",
            "Inwentaryzacja aktywów informacyjnych",
        ),
        (
            "iso27001_internal_audit",
            "ISMS Internal Audit Report",
            True,
            "security",
            "https://www.iso.org/standard/27001",
            "Raport audytu wewnętrznego ISMS (Art. 9.2)",
        ),
        (
            "iso27001_mgmt_review",
            "Management Review Minutes (ISMS)",
            True,
            "security",
            "https://www.iso.org/standard/27001",
            "Protokół przeglądu zarządzania ISMS (Art. 9.3)",
        ),
        (
            "iso27001_corrective_action",
            "Corrective Action Record (ISMS)",
            True,
            "security",
            "https://www.iso.org/standard/27001",
            "Zapis działania korygującego (Art. 10.1)",
        ),
        (
            "iso27001_objectives",
            "Information Security Objectives",
            True,
            "security",
            "https://www.iso.org/standard/27001",
            "Cele bezpieczeństwa informacji (Art. 6.2)",
        ),
    ],
    # ── ISO/IEC 27002 — praktyki bezpieczeństwa ────────────────────────────
    "ISO/IEC 27002": [
        (
            "iso27002_access_policy",
            "Access Control Policy",
            True,
            "security",
            "https://www.iso.org/standard/75652.html",
            "Polityka kontroli dostępu",
        ),
        (
            "iso27002_crypto_policy",
            "Cryptography Policy",
            True,
            "security",
            "https://www.iso.org/standard/75652.html",
            "Polityka kryptografii",
        ),
        (
            "iso27002_asset_mgmt_policy",
            "Asset Management Policy",
            True,
            "security",
            "https://www.iso.org/standard/75652.html",
            "Polityka zarządzania aktywami",
        ),
        (
            "iso27002_supplier_policy",
            "Supplier Security Policy",
            True,
            "security",
            "https://www.iso.org/standard/75652.html",
            "Polityka bezpieczeństwa dostawców",
        ),
        (
            "iso27002_incident_proc",
            "Incident Management Procedure",
            True,
            "security",
            "https://www.iso.org/standard/75652.html",
            "Procedura zarządzania incydentami",
        ),
        (
            "iso27002_audit_log_policy",
            "Audit Logging Policy",
            True,
            "security",
            "https://www.iso.org/standard/75652.html",
            "Polityka dzienników audytu",
        ),
        (
            "iso27002_security_awareness",
            "Security Awareness Training Plan",
            True,
            "security",
            "https://www.iso.org/standard/75652.html",
            "Plan szkoleń z bezpieczeństwa",
        ),
    ],
    # ── ISO/IEC 27005 — zarządzanie ryzykiem bezpieczeństwa ───────────────
    "ISO/IEC 27005": [
        (
            "iso27005_risk_context",
            "Risk Management Context",
            True,
            "security",
            "https://www.iso.org/standard/80585.html",
            "Kontekst zarządzania ryzykiem",
        ),
        (
            "iso27005_risk_register",
            "Information Security Risk Register",
            True,
            "security",
            "https://www.iso.org/standard/80585.html",
            "Rejestr ryzyk bezpieczeństwa",
        ),
        (
            "iso27005_risk_assessment_rpt",
            "Risk Assessment Report",
            True,
            "security",
            "https://www.iso.org/standard/80585.html",
            "Raport z oceny ryzyka",
        ),
        (
            "iso27005_risk_treatment_plan",
            "Risk Treatment Plan",
            True,
            "security",
            "https://www.iso.org/standard/80585.html",
            "Plan postępowania z ryzykami",
        ),
        (
            "iso27005_monitoring_report",
            "Risk Monitoring and Review Report",
            True,
            "security",
            "https://www.iso.org/standard/80585.html",
            "Raport monitorowania i przeglądu ryzyk",
        ),
    ],
    # ── ISO/IEC 27017 — bezpieczeństwo w chmurze ──────────────────────────
    "ISO/IEC 27017": [
        (
            "iso27017_cloud_security_policy",
            "Cloud Security Policy",
            True,
            "cloud",
            "https://www.iso.org/standard/43757.html",
            "Polityka bezpieczeństwa usług chmurowych",
        ),
        (
            "iso27017_shared_responsibility",
            "Shared Responsibility Matrix",
            True,
            "cloud",
            "https://www.iso.org/standard/43757.html",
            "Macierz odpowiedzialności dostawca/klient chmury",
        ),
        (
            "iso27017_cloud_asset_inv",
            "Cloud Asset Inventory",
            True,
            "cloud",
            "https://www.iso.org/standard/43757.html",
            "Inwentaryzacja zasobów w chmurze",
        ),
        (
            "iso27017_virtual_env_policy",
            "Virtual Environment Security Policy",
            True,
            "cloud",
            "https://www.iso.org/standard/43757.html",
            "Polityka bezpieczeństwa środowisk wirtualnych",
        ),
    ],
    # ── ISO/IEC 27018 — ochrona PII w chmurze ────────────────────────────
    "ISO/IEC 27018": [
        (
            "iso27018_pii_policy",
            "PII Protection Policy (Cloud)",
            True,
            "privacy",
            "https://www.iso.org/standard/76559.html",
            "Polityka ochrony danych osobowych w chmurze",
        ),
        (
            "iso27018_consent_mgmt",
            "Consent Management Procedure",
            True,
            "privacy",
            "https://www.iso.org/standard/76559.html",
            "Procedura zarządzania zgodami",
        ),
        (
            "iso27018_pii_inventory",
            "PII Inventory (Cloud)",
            True,
            "privacy",
            "https://www.iso.org/standard/76559.html",
            "Inwentaryzacja danych osobowych w chmurze",
        ),
        (
            "iso27018_incident_notify",
            "PII Incident Notification Procedure",
            True,
            "privacy",
            "https://www.iso.org/standard/76559.html",
            "Procedura powiadamiania o incydentach PII",
        ),
    ],
    # ── ISO/IEC 27035 — zarządzanie incydentami ────────────────────────────
    "ISO/IEC 27035": [
        (
            "iso27035_incident_policy",
            "Information Security Incident Policy",
            True,
            "security",
            "https://www.iso.org/standard/74598.html",
            "Polityka zarządzania incydentami bezpieczeństwa",
        ),
        (
            "iso27035_incident_plan",
            "Incident Response Plan",
            True,
            "security",
            "https://www.iso.org/standard/74598.html",
            "Plan reagowania na incydenty bezpieczeństwa",
        ),
        (
            "iso27035_incident_log",
            "Incident Log",
            True,
            "security",
            "https://www.iso.org/standard/74598.html",
            "Dziennik incydentów bezpieczeństwa",
        ),
        (
            "iso27035_incident_report",
            "Incident Investigation Report",
            True,
            "security",
            "https://www.iso.org/standard/74598.html",
            "Raport z dochodzenia po incydencie",
        ),
        (
            "iso27035_lessons_learned",
            "Lessons Learned Report (Incident)",
            True,
            "security",
            "https://www.iso.org/standard/74598.html",
            "Raport wniosków po incydencie",
        ),
    ],
    # ── ISO/IEC 27701 — PIMS ─────────────────────────────────────────────
    "ISO/IEC 27701": [
        (
            "iso27701_pims_policy",
            "Privacy Information Management Policy",
            True,
            "privacy",
            "https://www.iso.org/standard/71671.html",
            "Polityka zarządzania informacjami o prywatności",
        ),
        (
            "iso27701_pii_processing",
            "PII Processing Register",
            True,
            "privacy",
            "https://www.iso.org/standard/71671.html",
            "Rejestr operacji przetwarzania danych osobowych",
        ),
        (
            "iso27701_privacy_notice",
            "Privacy Notice / Privacy Policy",
            True,
            "privacy",
            "https://www.iso.org/standard/71671.html",
            "Informacja/polityka prywatności dla osób",
        ),
        (
            "iso27701_dpia",
            "Data Protection Impact Assessment",
            True,
            "privacy",
            "https://www.iso.org/standard/71671.html",
            "Ocena skutków dla ochrony danych",
        ),
        (
            "iso27701_dpa_agreement",
            "Data Processing Agreement (DPA)",
            True,
            "privacy",
            "https://www.iso.org/standard/71671.html",
            "Umowa powierzenia przetwarzania danych",
        ),
    ],
    # ── ISO/IEC 29110 — małe organizacje ─────────────────────────────────
    "ISO/IEC 29110": [
        (
            "iso29110_project_plan",
            "Project Plan",
            True,
            "process",
            "https://www.iso.org/standard/74590.html",
            "Plan projektu dla małej jednostki (VSE)",
        ),
        (
            "iso29110_req_spec",
            "Software Requirements Specification",
            True,
            "requirements",
            "https://www.iso.org/standard/74590.html",
            "Specyfikacja wymagań",
        ),
        (
            "iso29110_config_log",
            "Configuration Log",
            True,
            "process",
            "https://www.iso.org/standard/74590.html",
            "Dziennik zarządzania konfiguracją",
        ),
        (
            "iso29110_acceptance_criteria",
            "Acceptance Criteria",
            True,
            "testing",
            "https://www.iso.org/standard/74590.html",
            "Kryteria akceptacji",
        ),
        (
            "iso29110_progress_report",
            "Progress Status Report",
            True,
            "process",
            "https://www.iso.org/standard/74590.html",
            "Raport postępu projektu",
        ),
        (
            "iso29110_delivery_record",
            "Delivery Record",
            True,
            "process",
            "https://www.iso.org/standard/74590.html",
            "Protokół odbioru/dostarczenia",
        ),
    ],
    # ── ISO/IEC 25010 — model jakości ─────────────────────────────────────
    "ISO/IEC 25010": [
        (
            "iso25010_quality_requirements",
            "Quality Requirements Specification",
            True,
            "quality",
            "https://www.iso.org/standard/78176.html",
            "Specyfikacja wymagań jakościowych (8 cech)",
        ),
        (
            "iso25010_quality_model_ref",
            "Quality Model Reference (per product)",
            False,
            "quality",
            "https://www.iso.org/standard/78176.html",
            "Odniesienie do cech jakości produktu",
        ),
        (
            "iso25010_nfr_specification",
            "Non-Functional Requirements Spec",
            True,
            "requirements",
            "https://www.iso.org/standard/78176.html",
            "Specyfikacja wymagań niefunkcjonalnych",
        ),
    ],
    # ── ISO/IEC 25040 — ocena jakości ────────────────────────────────────
    "ISO/IEC 25040": [
        (
            "iso25040_eval_plan",
            "Evaluation Plan",
            True,
            "quality",
            "https://www.iso.org/standard/35747.html",
            "Plan oceny jakości produktu",
        ),
        (
            "iso25040_eval_specification",
            "Evaluation Specification",
            True,
            "quality",
            "https://www.iso.org/standard/35747.html",
            "Specyfikacja oceny — kryteria, miary",
        ),
        (
            "iso25040_eval_report",
            "Evaluation Report",
            True,
            "quality",
            "https://www.iso.org/standard/35747.html",
            "Raport z oceny jakości produktu",
        ),
    ],
    # ── ISO/IEC 20546 — Big Data ──────────────────────────────────────────
    "ISO/IEC 20546": [
        (
            "iso20546_bd_arch",
            "Big Data Architecture Description",
            True,
            "data",
            "https://www.iso.org/standard/68305.html",
            "Opis architektury Big Data",
        ),
        (
            "iso20546_data_governance",
            "Data Governance Policy",
            True,
            "data",
            "https://www.iso.org/standard/68305.html",
            "Polityka ładu danych",
        ),
        (
            "iso20546_data_dictionary",
            "Data Dictionary",
            True,
            "data",
            "https://www.iso.org/standard/68305.html",
            "Słownik danych",
        ),
        (
            "iso20546_data_quality",
            "Data Quality Framework",
            False,
            "data",
            "https://www.iso.org/standard/68305.html",
            "Framework jakości danych",
        ),
    ],
    # ── ISO/IEC 23053 — AI/ML framework ──────────────────────────────────
    "ISO/IEC 23053": [
        (
            "iso23053_ml_system_arch",
            "ML System Architecture Description",
            True,
            "ai",
            "https://www.iso.org/standard/74438.html",
            "Opis architektury systemu uczenia maszynowego",
        ),
        (
            "iso23053_model_card",
            "Model Card / Model Documentation",
            True,
            "ai",
            "https://www.iso.org/standard/74438.html",
            "Karta modelu ML: cel, dane, ograniczenia",
        ),
        (
            "iso23053_data_spec",
            "Training Data Specification",
            True,
            "ai",
            "https://www.iso.org/standard/74438.html",
            "Specyfikacja danych treningowych",
        ),
        (
            "iso23053_eval_plan",
            "ML Model Evaluation Plan",
            True,
            "ai",
            "https://www.iso.org/standard/74438.html",
            "Plan ewaluacji modelu ML",
        ),
    ],
    # ── ISO/IEC 38500 — ład informatyczny ─────────────────────────────────
    "ISO/IEC 38500": [
        (
            "iso38500_it_governance_policy",
            "IT Governance Policy",
            True,
            "governance",
            "https://www.iso.org/standard/62816.html",
            "Polityka ładu informatycznego organizacji",
        ),
        (
            "iso38500_it_strategy",
            "IT Strategy",
            True,
            "governance",
            "https://www.iso.org/standard/62816.html",
            "Strategia IT",
        ),
        (
            "iso38500_it_portfolio",
            "IT Portfolio / Investment Plan",
            False,
            "governance",
            "https://www.iso.org/standard/62816.html",
            "Portfel IT / plan inwestycji",
        ),
        (
            "iso38500_perf_report",
            "IT Performance Report",
            False,
            "governance",
            "https://www.iso.org/standard/62816.html",
            "Raport wydajności IT",
        ),
    ],
    # ── ISO/IEC 42001 — AIMS (AI Management System) ────────────────────────
    "ISO/IEC 42001": [
        (
            "iso42001_aims_policy",
            "AI Policy",
            True,
            "ai",
            "https://www.iso.org/standard/81230.html",
            "Polityka zarządzania sztuczną inteligencją",
        ),
        (
            "iso42001_ai_risk_assessment",
            "AI Risk Assessment",
            True,
            "ai",
            "https://www.iso.org/standard/81230.html",
            "Ocena ryzyk związanych z AI",
        ),
        (
            "iso42001_ai_impact_assessment",
            "AI Impact Assessment (AIIA)",
            True,
            "ai",
            "https://www.iso.org/standard/81230.html",
            "Ocena wpływu systemu AI na osoby i społeczeństwo",
        ),
        (
            "iso42001_ai_incident_log",
            "AI Incident Log",
            True,
            "ai",
            "https://www.iso.org/standard/81230.html",
            "Dziennik incydentów systemów AI",
        ),
        (
            "iso42001_ai_governance",
            "AI Governance Framework",
            True,
            "ai",
            "https://www.iso.org/standard/81230.html",
            "Framework zarządzania AI w organizacji",
        ),
        (
            "iso42001_objectives",
            "AI Objectives",
            True,
            "ai",
            "https://www.iso.org/standard/81230.html",
            "Cele AIMS (Art. 6.2)",
        ),
    ],
    # ── ITIL 4 ────────────────────────────────────────────────────────────
    "ITIL 4": [
        (
            "itil4_service_catalog",
            "Service Catalog",
            True,
            "itsm",
            "https://www.axelos.com/certifications/itil-service-management/",
            "Katalog usług IT",
        ),
        (
            "itil4_service_design",
            "Service Design Package",
            True,
            "itsm",
            "https://www.axelos.com/certifications/itil-service-management/",
            "Pakiet projektowania usługi",
        ),
        (
            "itil4_sla",
            "Service Level Agreement (SLA)",
            True,
            "itsm",
            "https://www.axelos.com/certifications/itil-service-management/",
            "Umowa o poziomie usług",
        ),
        (
            "itil4_ola",
            "Operational Level Agreement (OLA)",
            False,
            "itsm",
            "https://www.axelos.com/certifications/itil-service-management/",
            "Umowa operacyjna między wewnętrznymi działami",
        ),
        (
            "itil4_incident_record",
            "Incident Record",
            True,
            "itsm",
            "https://www.axelos.com/certifications/itil-service-management/",
            "Rekord incydentu",
        ),
        (
            "itil4_problem_record",
            "Problem Record",
            True,
            "itsm",
            "https://www.axelos.com/certifications/itil-service-management/",
            "Rekord problemu",
        ),
        (
            "itil4_change_request",
            "Change Request",
            True,
            "itsm",
            "https://www.axelos.com/certifications/itil-service-management/",
            "Wniosek o zmianę",
        ),
        (
            "itil4_cmdb",
            "Configuration Management Database (CMDB)",
            True,
            "itsm",
            "https://www.axelos.com/certifications/itil-service-management/",
            "Baza danych zarządzania konfiguracją",
        ),
        (
            "itil4_known_error_record",
            "Known Error Record",
            False,
            "itsm",
            "https://www.axelos.com/certifications/itil-service-management/",
            "Rekord znanych błędów",
        ),
        (
            "itil4_release_plan",
            "Release Plan",
            True,
            "itsm",
            "https://www.axelos.com/certifications/itil-service-management/",
            "Plan wydania usługi",
        ),
        (
            "itil4_service_report",
            "Service Performance Report",
            True,
            "itsm",
            "https://www.axelos.com/certifications/itil-service-management/",
            "Raport wydajności usługi",
        ),
        (
            "itil4_csi_register",
            "Continual Improvement Register",
            False,
            "itsm",
            "https://www.axelos.com/certifications/itil-service-management/",
            "Rejestr ciągłego doskonalenia",
        ),
    ],
    # ── TOGAF ADM ────────────────────────────────────────────────────────
    "TOGAF ADM": [
        (
            "togaf_arch_vision",
            "Architecture Vision",
            True,
            "architecture",
            "https://www.opengroup.org/togaf/",
            "Wizja architektoniczna (Phase A)",
        ),
        (
            "togaf_business_arch",
            "Business Architecture",
            True,
            "architecture",
            "https://www.opengroup.org/togaf/",
            "Architektura biznesowa (Phase B)",
        ),
        (
            "togaf_data_arch",
            "Data Architecture",
            True,
            "architecture",
            "https://www.opengroup.org/togaf/",
            "Architektura danych (Phase C)",
        ),
        (
            "togaf_app_arch",
            "Applications Architecture",
            True,
            "architecture",
            "https://www.opengroup.org/togaf/",
            "Architektura aplikacji (Phase C)",
        ),
        (
            "togaf_tech_arch",
            "Technology Architecture",
            True,
            "architecture",
            "https://www.opengroup.org/togaf/",
            "Architektura technologiczna (Phase D)",
        ),
        (
            "togaf_gap_analysis",
            "Gap Analysis",
            True,
            "architecture",
            "https://www.opengroup.org/togaf/",
            "Analiza luk bieżąca vs docelowa architektura",
        ),
        (
            "togaf_migration_plan",
            "Architecture Migration Plan",
            True,
            "architecture",
            "https://www.opengroup.org/togaf/",
            "Plan migracji architektonicznej (Phase F)",
        ),
        (
            "togaf_arch_roadmap",
            "Architecture Roadmap",
            True,
            "architecture",
            "https://www.opengroup.org/togaf/",
            "Mapa drogowa architektury",
        ),
        (
            "togaf_arch_req_spec",
            "Architecture Requirements Specification",
            True,
            "architecture",
            "https://www.opengroup.org/togaf/",
            "Specyfikacja wymagań architektonicznych",
        ),
        (
            "togaf_arch_contract",
            "Architecture Contract",
            False,
            "architecture",
            "https://www.opengroup.org/togaf/",
            "Kontrakt architektoniczny między działami",
        ),
    ],
    # ── PMBOK 7 ────────────────────────────────────────────────────────────
    "PMBOK 7": [
        (
            "pmbok7_project_charter",
            "Project Charter",
            True,
            "project_mgmt",
            "https://www.pmi.org/pmbok-guide-standards/foundational/pmbok",
            "Karta projektu",
        ),
        (
            "pmbok7_scope_baseline",
            "Scope Baseline (WBS + WBS Dict + Scope Stmt)",
            True,
            "project_mgmt",
            "https://www.pmi.org/pmbok-guide-standards/foundational/pmbok",
            "Linia bazowa zakresu",
        ),
        (
            "pmbok7_schedule_baseline",
            "Schedule Baseline",
            True,
            "project_mgmt",
            "https://www.pmi.org/pmbok-guide-standards/foundational/pmbok",
            "Linia bazowa harmonogramu",
        ),
        (
            "pmbok7_cost_baseline",
            "Cost Baseline",
            True,
            "project_mgmt",
            "https://www.pmi.org/pmbok-guide-standards/foundational/pmbok",
            "Linia bazowa kosztów",
        ),
        (
            "pmbok7_quality_mgmt_plan",
            "Quality Management Plan",
            True,
            "project_mgmt",
            "https://www.pmi.org/pmbok-guide-standards/foundational/pmbok",
            "Plan zarządzania jakością projektu",
        ),
        (
            "pmbok7_risk_register",
            "Risk Register",
            True,
            "project_mgmt",
            "https://www.pmi.org/pmbok-guide-standards/foundational/pmbok",
            "Rejestr ryzyk projektu",
        ),
        (
            "pmbok7_stakeholder_register",
            "Stakeholder Register",
            True,
            "project_mgmt",
            "https://www.pmi.org/pmbok-guide-standards/foundational/pmbok",
            "Rejestr interesariuszy",
        ),
        (
            "pmbok7_comms_mgmt_plan",
            "Communications Management Plan",
            True,
            "project_mgmt",
            "https://www.pmi.org/pmbok-guide-standards/foundational/pmbok",
            "Plan zarządzania komunikacją",
        ),
        (
            "pmbok7_change_log",
            "Change Log",
            True,
            "project_mgmt",
            "https://www.pmi.org/pmbok-guide-standards/foundational/pmbok",
            "Dziennik zmian projektu",
        ),
        (
            "pmbok7_issue_log",
            "Issue Log",
            True,
            "project_mgmt",
            "https://www.pmi.org/pmbok-guide-standards/foundational/pmbok",
            "Dziennik problemów/zagadnień",
        ),
        (
            "pmbok7_lessons_learned",
            "Lessons Learned Register",
            True,
            "project_mgmt",
            "https://www.pmi.org/pmbok-guide-standards/foundational/pmbok",
            "Rejestr wniosków z projektu",
        ),
        (
            "pmbok7_project_mgmt_plan",
            "Project Management Plan",
            True,
            "project_mgmt",
            "https://www.pmi.org/pmbok-guide-standards/foundational/pmbok",
            "Plan zarządzania projektem (integralny)",
        ),
        (
            "pmbok7_status_report",
            "Project Status Report",
            False,
            "project_mgmt",
            "https://www.pmi.org/pmbok-guide-standards/foundational/pmbok",
            "Raport statusu projektu",
        ),
        (
            "pmbok7_procurement_docs",
            "Procurement Documents",
            False,
            "project_mgmt",
            "https://www.pmi.org/pmbok-guide-standards/foundational/pmbok",
            "Dokumenty zamówień",
        ),
    ],
    # ── PRINCE2 7 ─────────────────────────────────────────────────────────
    "PRINCE2 7": [
        (
            "prince2_project_brief",
            "Project Brief",
            True,
            "project_mgmt",
            "https://www.axelos.com/certifications/propath/prince2-project-management/",
            "Krótki opis projektu (pre-initiation)",
        ),
        (
            "prince2_pid",
            "Project Initiation Documentation (PID)",
            True,
            "project_mgmt",
            "https://www.axelos.com/certifications/propath/prince2-project-management/",
            "Dokumentacja inicjalizacji projektu",
        ),
        (
            "prince2_business_case",
            "Business Case",
            True,
            "project_mgmt",
            "https://www.axelos.com/certifications/propath/prince2-project-management/",
            "Uzasadnienie biznesowe projektu",
        ),
        (
            "prince2_risk_register",
            "Risk Register",
            True,
            "project_mgmt",
            "https://www.axelos.com/certifications/propath/prince2-project-management/",
            "Rejestr ryzyk PRINCE2",
        ),
        (
            "prince2_quality_register",
            "Quality Register",
            True,
            "project_mgmt",
            "https://www.axelos.com/certifications/propath/prince2-project-management/",
            "Rejestr jakości",
        ),
        (
            "prince2_issue_register",
            "Issue Register",
            True,
            "project_mgmt",
            "https://www.axelos.com/certifications/propath/prince2-project-management/",
            "Rejestr zagadnień",
        ),
        (
            "prince2_lessons_log",
            "Lessons Log",
            True,
            "project_mgmt",
            "https://www.axelos.com/certifications/propath/prince2-project-management/",
            "Dziennik wniosków",
        ),
        (
            "prince2_product_desc",
            "Product Description",
            True,
            "project_mgmt",
            "https://www.axelos.com/certifications/propath/prince2-project-management/",
            "Opis produktu",
        ),
        (
            "prince2_stage_plan",
            "Stage Plan",
            True,
            "project_mgmt",
            "https://www.axelos.com/certifications/propath/prince2-project-management/",
            "Plan etapu",
        ),
        (
            "prince2_end_project_report",
            "End Project Report",
            True,
            "project_mgmt",
            "https://www.axelos.com/certifications/propath/prince2-project-management/",
            "Raport zamknięcia projektu",
        ),
        (
            "prince2_highlight_report",
            "Highlight Report",
            True,
            "project_mgmt",
            "https://www.axelos.com/certifications/propath/prince2-project-management/",
            "Raport wyróżnień (periody)",
        ),
        (
            "prince2_exception_report",
            "Exception Report",
            True,
            "project_mgmt",
            "https://www.axelos.com/certifications/propath/prince2-project-management/",
            "Raport wyjątku",
        ),
    ],
    # ── SAFe 6.0 ──────────────────────────────────────────────────────────
    "SAFe 6.0": [
        (
            "safe_pi_plan",
            "PI Planning Inputs (Vision, Backlog)",
            True,
            "agile",
            "https://scaledagileframework.com/pi-planning/",
            "Wejścia do planowania Przyrostu Programu",
        ),
        (
            "safe_pi_objectives",
            "PI Objectives",
            True,
            "agile",
            "https://scaledagileframework.com/pi-objectives/",
            "Cele PI per zespół i ART",
        ),
        (
            "safe_team_iteration_plan",
            "Team Iteration Plan",
            True,
            "agile",
            "https://scaledagileframework.com/iteration-planning/",
            "Plan iteracji zespołu",
        ),
        (
            "safe_system_demo",
            "System Demo",
            True,
            "agile",
            "https://scaledagileframework.com/system-demo/",
            "Demonstracja systemu na poziomie ART",
        ),
        (
            "safe_inspect_adapt",
            "Inspect and Adapt Report",
            True,
            "agile",
            "https://scaledagileframework.com/inspect-and-adapt/",
            "Raport I&A — retrospektywa PI",
        ),
        (
            "safe_arch_runway",
            "Architectural Runway Documentation",
            False,
            "agile",
            "https://scaledagileframework.com/architectural-runway/",
            "Dokumentacja pasa startowego architektury",
        ),
        (
            "safe_value_stream_mapping",
            "Value Stream Mapping",
            False,
            "agile",
            "https://scaledagileframework.com/value-streams/",
            "Mapowanie strumienia wartości",
        ),
        (
            "safe_portfolio_kanban",
            "Portfolio Kanban",
            False,
            "agile",
            "https://scaledagileframework.com/portfolio-kanban/",
            "Portfolio Kanban — pipeline epics",
        ),
    ],
    # ── SCRUM Guide ──────────────────────────────────────────────────────
    "SCRUM Guide": [
        (
            "scrum_product_backlog",
            "Product Backlog",
            True,
            "agile",
            "https://scrumguides.org/",
            "Zaległości produktu — uporządkowana lista pracy",
        ),
        (
            "scrum_sprint_backlog",
            "Sprint Backlog",
            True,
            "agile",
            "https://scrumguides.org/",
            "Zaległości sprintu — plan sprintu + backlog",
        ),
        (
            "scrum_increment",
            "Increment",
            True,
            "agile",
            "https://scrumguides.org/",
            "Przyrost — działający produkt po sprincie",
        ),
        (
            "scrum_definition_of_done",
            "Definition of Done (DoD)",
            True,
            "agile",
            "https://scrumguides.org/",
            "Definicja Ukończenia",
        ),
        (
            "scrum_sprint_goal",
            "Sprint Goal",
            True,
            "agile",
            "https://scrumguides.org/",
            "Cel sprintu",
        ),
        (
            "scrum_product_goal",
            "Product Goal",
            True,
            "agile",
            "https://scrumguides.org/",
            "Cel produktu",
        ),
        (
            "scrum_sprint_review_notes",
            "Sprint Review Notes",
            False,
            "agile",
            "https://scrumguides.org/",
            "Notatki z przeglądu sprintu",
        ),
        (
            "scrum_sprint_retro_notes",
            "Sprint Retrospective Notes",
            False,
            "agile",
            "https://scrumguides.org/",
            "Notatki z retrospektywy sprintu",
        ),
    ],
    # ── GDPR / RODO ──────────────────────────────────────────────────────
    "GDPR / RODO": [
        (
            "gdpr_privacy_policy",
            "Privacy Policy / Privacy Notice",
            True,
            "privacy",
            "https://eur-lex.europa.eu/eli/reg/2016/679/oj",
            "Polityka prywatności / informacja o przetwarzaniu (Art. 13/14)",
        ),
        (
            "gdpr_rop",
            "Record of Processing Activities (RoPA)",
            True,
            "privacy",
            "https://eur-lex.europa.eu/eli/reg/2016/679/oj",
            "Rejestr czynności przetwarzania (Art. 30)",
        ),
        (
            "gdpr_dpia",
            "Data Protection Impact Assessment (DPIA)",
            True,
            "privacy",
            "https://eur-lex.europa.eu/eli/reg/2016/679/oj",
            "Ocena skutków dla ochrony danych (Art. 35)",
        ),
        (
            "gdpr_dpa",
            "Data Processing Agreement (DPA)",
            True,
            "privacy",
            "https://eur-lex.europa.eu/eli/reg/2016/679/oj",
            "Umowa powierzenia przetwarzania danych (Art. 28)",
        ),
        (
            "gdpr_breach_notification",
            "Data Breach Notification",
            True,
            "privacy",
            "https://eur-lex.europa.eu/eli/reg/2016/679/oj",
            "Zgłoszenie naruszenia ochrony danych (Art. 33/34)",
        ),
        (
            "gdpr_consent_form",
            "Consent Form",
            True,
            "privacy",
            "https://eur-lex.europa.eu/eli/reg/2016/679/oj",
            "Formularz zgody na przetwarzanie (Art. 7)",
        ),
        (
            "gdpr_data_retention_policy",
            "Data Retention Policy",
            True,
            "privacy",
            "https://eur-lex.europa.eu/eli/reg/2016/679/oj",
            "Polityka retencji danych",
        ),
        (
            "gdpr_subject_rights_procedure",
            "Data Subject Rights Procedure",
            True,
            "privacy",
            "https://eur-lex.europa.eu/eli/reg/2016/679/oj",
            "Procedura realizacji praw osób (Art. 15-22)",
        ),
    ],
    # ── DORA ─────────────────────────────────────────────────────────────
    "DORA": [
        (
            "dora_ict_risk_framework",
            "ICT Risk Management Framework",
            True,
            "compliance",
            "https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX%3A32022R2554",
            "Framework zarządzania ryzykiem ICT (Art. 6)",
        ),
        (
            "dora_incident_classification",
            "ICT Incident Classification Policy",
            True,
            "compliance",
            "https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX%3A32022R2554",
            "Polityka klasyfikacji incydentów ICT (Art. 17)",
        ),
        (
            "dora_major_incident_report",
            "Major ICT Incident Report",
            True,
            "compliance",
            "https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX%3A32022R2554",
            "Raport poważnego incydentu ICT dla regulatora (Art. 19)",
        ),
        (
            "dora_drt_plan",
            "Digital Operational Resilience Testing Plan",
            True,
            "compliance",
            "https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX%3A32022R2554",
            "Plan testowania odporności cyfrowej (Art. 24)",
        ),
        (
            "dora_tlpt_report",
            "Threat-Led Penetration Testing (TLPT) Report",
            False,
            "compliance",
            "https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX%3A32022R2554",
            "Raport TLPT — zaawansowane testy penetracyjne (Art. 26)",
        ),
        (
            "dora_third_party_register",
            "ICT Third-Party Provider Register",
            True,
            "compliance",
            "https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX%3A32022R2554",
            "Rejestr dostawców usług ICT (Art. 28)",
        ),
        (
            "dora_contractual_arrangements",
            "Contractual Arrangements with ICT Providers",
            True,
            "compliance",
            "https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX%3A32022R2554",
            "Umowy z dostawcami usług ICT (Art. 30)",
        ),
    ],
    # ── NIS2 ─────────────────────────────────────────────────────────────
    "NIS2": [
        (
            "nis2_security_policy",
            "Network and Information Systems Security Policy",
            True,
            "compliance",
            "https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX%3A32022L2555",
            "Polityka bezpieczeństwa sieci i systemów informacyjnych",
        ),
        (
            "nis2_risk_assessment",
            "Cybersecurity Risk Assessment (NIS2)",
            True,
            "compliance",
            "https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX%3A32022L2555",
            "Ocena ryzyka cyberbezpieczeństwa (Art. 21)",
        ),
        (
            "nis2_incident_handling",
            "Incident Handling Procedures (NIS2)",
            True,
            "compliance",
            "https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX%3A32022L2555",
            "Procedury obsługi incydentów",
        ),
        (
            "nis2_incident_notification",
            "Incident Notification Report (NIS2)",
            True,
            "compliance",
            "https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX%3A32022L2555",
            "Zgłoszenie incydentu do CSIRT/organu (Art. 23)",
        ),
        (
            "nis2_bcp",
            "Business Continuity Plan (NIS2)",
            True,
            "compliance",
            "https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX%3A32022L2555",
            "Plan ciągłości działania",
        ),
        (
            "nis2_supply_chain_policy",
            "Supply Chain Security Policy",
            True,
            "compliance",
            "https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX%3A32022L2555",
            "Polityka bezpieczeństwa łańcucha dostaw (Art. 21.2.d)",
        ),
    ],
    # ── NIST CSF ─────────────────────────────────────────────────────────
    "NIST CSF": [
        (
            "nistcsf_cyber_policy",
            "Cybersecurity Policy",
            True,
            "security",
            "https://www.nist.gov/cyberframework",
            "Polityka cyberbezpieczeństwa organizacji",
        ),
        (
            "nistcsf_asset_inventory",
            "Asset Inventory",
            True,
            "security",
            "https://www.nist.gov/cyberframework",
            "Inwentaryzacja aktywów (IDENTIFY/ID.AM)",
        ),
        (
            "nistcsf_risk_assessment",
            "Cybersecurity Risk Assessment",
            True,
            "security",
            "https://www.nist.gov/cyberframework",
            "Ocena ryzyka cyberbezpieczeństwa (IDENTIFY/ID.RA)",
        ),
        (
            "nistcsf_incident_response_plan",
            "Incident Response Plan",
            True,
            "security",
            "https://www.nist.gov/cyberframework",
            "Plan reagowania na incydenty (RESPOND/RS.RP)",
        ),
        (
            "nistcsf_recovery_plan",
            "Cybersecurity Recovery Plan",
            True,
            "security",
            "https://www.nist.gov/cyberframework",
            "Plan odtwarzania (RECOVER/RC.RP)",
        ),
        (
            "nistcsf_access_control",
            "Access Control Policy",
            True,
            "security",
            "https://www.nist.gov/cyberframework",
            "Polityka kontroli dostępu (PROTECT/PR.AC)",
        ),
        (
            "nistcsf_awareness_training",
            "Security Awareness Training Plan",
            True,
            "security",
            "https://www.nist.gov/cyberframework",
            "Plan szkoleń z bezpieczeństwa (PROTECT/PR.AT)",
        ),
        (
            "nistcsf_data_protection",
            "Data Protection Policy",
            True,
            "security",
            "https://www.nist.gov/cyberframework",
            "Polityka ochrony danych (PROTECT/PR.DS)",
        ),
    ],
    # ── NIST SP 800-53 ────────────────────────────────────────────────────
    "NIST SP 800-53": [
        (
            "nist80053_security_plan",
            "System Security Plan (SSP)",
            True,
            "security",
            "https://csrc.nist.gov/publications/detail/sp/800-53/rev-5/final",
            "Plan bezpieczeństwa systemu (kontrola PL-2)",
        ),
        (
            "nist80053_privacy_plan",
            "Privacy Plan",
            True,
            "privacy",
            "https://csrc.nist.gov/publications/detail/sp/800-53/rev-5/final",
            "Plan prywatności systemu",
        ),
        (
            "nist80053_poam",
            "Plan of Action and Milestones (POA&M)",
            True,
            "security",
            "https://csrc.nist.gov/publications/detail/sp/800-53/rev-5/final",
            "Plan działań i kamieni milowych — śledzenie remediacji",
        ),
        (
            "nist80053_sar",
            "Security Assessment Report (SAR)",
            True,
            "security",
            "https://csrc.nist.gov/publications/detail/sp/800-53/rev-5/final",
            "Raport oceny bezpieczeństwa",
        ),
        (
            "nist80053_ato",
            "Authorization to Operate (ATO)",
            True,
            "security",
            "https://csrc.nist.gov/publications/detail/sp/800-53/rev-5/final",
            "Autoryzacja do działania — decyzja organu",
        ),
        (
            "nist80053_ir_plan",
            "Incident Response Plan",
            True,
            "security",
            "https://csrc.nist.gov/publications/detail/sp/800-53/rev-5/final",
            "Plan reagowania na incydenty (IR-8)",
        ),
        (
            "nist80053_contingency_plan",
            "Contingency Plan",
            True,
            "security",
            "https://csrc.nist.gov/publications/detail/sp/800-53/rev-5/final",
            "Plan awaryjny (CP-2)",
        ),
        (
            "nist80053_config_mgmt_plan",
            "Configuration Management Plan (ISCM)",
            True,
            "security",
            "https://csrc.nist.gov/publications/detail/sp/800-53/rev-5/final",
            "Plan zarządzania konfiguracją (CM-9)",
        ),
    ],
    # ── CIS Controls v8 ───────────────────────────────────────────────────
    "CIS Controls v8": [
        (
            "cis_asset_inventory_hw",
            "Hardware Asset Inventory",
            True,
            "security",
            "https://www.cisecurity.org/controls/v8",
            "Inwentaryzacja sprzętu (CIS #1)",
        ),
        (
            "cis_asset_inventory_sw",
            "Software Asset Inventory",
            True,
            "security",
            "https://www.cisecurity.org/controls/v8",
            "Inwentaryzacja oprogramowania (CIS #2)",
        ),
        (
            "cis_data_mgmt_policy",
            "Data Management Policy",
            True,
            "security",
            "https://www.cisecurity.org/controls/v8",
            "Polityka zarządzania danymi (CIS #3)",
        ),
        (
            "cis_vulnerability_mgmt",
            "Vulnerability Management Program",
            True,
            "security",
            "https://www.cisecurity.org/controls/v8",
            "Program zarządzania podatnościami (CIS #7)",
        ),
        (
            "cis_audit_log_mgmt",
            "Audit Log Management Policy",
            True,
            "security",
            "https://www.cisecurity.org/controls/v8",
            "Polityka zarządzania dziennikami audytu (CIS #8)",
        ),
        (
            "cis_ir_plan",
            "Incident Response Plan (CIS)",
            True,
            "security",
            "https://www.cisecurity.org/controls/v8",
            "Plan reagowania na incydenty (CIS #17)",
        ),
        (
            "cis_pentest_plan",
            "Penetration Testing Plan",
            True,
            "security",
            "https://www.cisecurity.org/controls/v8",
            "Plan testów penetracyjnych (CIS #18)",
        ),
        (
            "cis_security_awareness",
            "Security Awareness Training Program",
            True,
            "security",
            "https://www.cisecurity.org/controls/v8",
            "Program szkoleń bezpieczeństwa (CIS #14)",
        ),
    ],
    # ── OWASP ASVS ───────────────────────────────────────────────────────
    "OWASP ASVS": [
        (
            "asvs_threat_model",
            "Threat Model",
            True,
            "security",
            "https://owasp.org/www-project-application-security-verification-standard/",
            "Model zagrożeń aplikacji (V1.1)",
        ),
        (
            "asvs_security_req_spec",
            "Security Requirements Specification",
            True,
            "security",
            "https://owasp.org/www-project-application-security-verification-standard/",
            "Specyfikacja wymagań bezpieczeństwa",
        ),
        (
            "asvs_sec_design_doc",
            "Secure Architecture & Design Doc",
            True,
            "security",
            "https://owasp.org/www-project-application-security-verification-standard/",
            "Dokumentacja bezpiecznej architektury",
        ),
        (
            "asvs_auth_design",
            "Authentication & Session Design",
            True,
            "security",
            "https://owasp.org/www-project-application-security-verification-standard/",
            "Projekt uwierzytelniania i sesji (V2, V3)",
        ),
        (
            "asvs_cryptography_policy",
            "Cryptography Policy (App Level)",
            True,
            "security",
            "https://owasp.org/www-project-application-security-verification-standard/",
            "Polityka kryptografii na poziomie aplikacji (V6)",
        ),
        (
            "asvs_error_handling",
            "Error Handling & Logging Design",
            True,
            "security",
            "https://owasp.org/www-project-application-security-verification-standard/",
            "Projekt obsługi błędów i logowania (V7, V8)",
        ),
        (
            "asvs_api_security_design",
            "API Security Design",
            True,
            "security",
            "https://owasp.org/www-project-application-security-verification-standard/",
            "Projekt bezpieczeństwa API (V14)",
        ),
    ],
    # ── OWASP MASVS ──────────────────────────────────────────────────────
    "OWASP MASVS": [
        (
            "masvs_mobile_threat_model",
            "Mobile Threat Model",
            True,
            "security",
            "https://mas.owasp.org/MASVS/",
            "Model zagrożeń aplikacji mobilnej",
        ),
        (
            "masvs_mobile_sec_req",
            "Mobile Security Requirements",
            True,
            "security",
            "https://mas.owasp.org/MASVS/",
            "Wymagania bezpieczeństwa aplikacji mobilnej",
        ),
        (
            "masvs_data_storage_design",
            "Secure Data Storage Design (Mobile)",
            True,
            "security",
            "https://mas.owasp.org/MASVS/",
            "Projekt bezpiecznego przechowywania danych (MASVS-STORAGE)",
        ),
        (
            "masvs_network_security_design",
            "Network Security Design (Mobile)",
            True,
            "security",
            "https://mas.owasp.org/MASVS/",
            "Projekt bezpieczeństwa sieci mobilnej (MASVS-NETWORK)",
        ),
        (
            "masvs_platform_interaction",
            "Platform Interaction Security Design",
            True,
            "security",
            "https://mas.owasp.org/MASVS/",
            "Projekt bezpieczeństwa interakcji z platformą",
        ),
        (
            "masvs_code_quality",
            "Code Quality and Resilience Design",
            True,
            "security",
            "https://mas.owasp.org/MASVS/",
            "Projekt jakości kodu i odporności (MASVS-RESILIENCE)",
        ),
    ],
    # ── OpenAPI 3.x ──────────────────────────────────────────────────────
    "OpenAPI 3.x": [
        (
            "openapi_spec",
            "OpenAPI Specification Document",
            True,
            "api",
            "https://spec.openapis.org/oas/v3.1.0",
            "Specyfikacja API w formacie OpenAPI 3.x (YAML/JSON)",
        ),
        (
            "openapi_api_design_guide",
            "API Design Guide",
            False,
            "api",
            "https://spec.openapis.org/oas/v3.1.0",
            "Przewodnik projektowania API (konwencje, wersjonowanie)",
        ),
        (
            "openapi_changelog",
            "API Changelog",
            False,
            "api",
            "https://spec.openapis.org/oas/v3.1.0",
            "Historia zmian API",
        ),
        (
            "openapi_auth_doc",
            "API Authentication Documentation",
            True,
            "api",
            "https://spec.openapis.org/oas/v3.1.0",
            "Dokumentacja uwierzytelniania API",
        ),
    ],
    # ── AsyncAPI 3.x ─────────────────────────────────────────────────────
    "AsyncAPI 3.x": [
        (
            "asyncapi_spec",
            "AsyncAPI Specification Document",
            True,
            "api",
            "https://www.asyncapi.com/docs/reference/specification/v3.0.0",
            "Specyfikacja asynchronicznego API w formacie AsyncAPI 3.x",
        ),
        (
            "asyncapi_event_catalog",
            "Event Catalog",
            True,
            "api",
            "https://www.asyncapi.com/docs/reference/specification/v3.0.0",
            "Katalog zdarzeń/wiadomości (event types, schemas)",
        ),
        (
            "asyncapi_channel_design",
            "Channel / Topic Design Document",
            False,
            "api",
            "https://www.asyncapi.com/docs/reference/specification/v3.0.0",
            "Projekt kanałów/tematów asynchronicznych",
        ),
    ],
    # ── HL7 FHIR ─────────────────────────────────────────────────────────
    "HL7 FHIR": [
        (
            "fhir_implementation_guide",
            "FHIR Implementation Guide (IG)",
            True,
            "health",
            "https://hl7.org/fhir/",
            "Przewodnik implementacji FHIR",
        ),
        (
            "fhir_resource_profiles",
            "FHIR Resource Profiles",
            True,
            "health",
            "https://hl7.org/fhir/",
            "Profile zasobów FHIR — ograniczenia i rozszerzenia",
        ),
        (
            "fhir_capability_statement",
            "CapabilityStatement / Conformance",
            True,
            "health",
            "https://hl7.org/fhir/",
            "Deklaracja możliwości serwera FHIR",
        ),
        (
            "fhir_value_sets",
            "ValueSet Definitions",
            True,
            "health",
            "https://hl7.org/fhir/",
            "Definicje zestawów wartości (kody medyczne)",
        ),
        (
            "fhir_integration_guide",
            "FHIR Integration Guide",
            False,
            "health",
            "https://hl7.org/fhir/",
            "Przewodnik integracji systemów przez FHIR",
        ),
    ],
    # ── PCI DSS ───────────────────────────────────────────────────────────
    "PCI DSS": [
        (
            "pcidss_cde_diagram",
            "Cardholder Data Environment (CDE) Diagram",
            True,
            "compliance",
            "https://www.pcisecuritystandards.org/",
            "Diagram środowiska danych posiadacza karty (Req. 1)",
        ),
        (
            "pcidss_network_diagram",
            "Network Diagram (PCI DSS)",
            True,
            "compliance",
            "https://www.pcisecuritystandards.org/",
            "Diagram sieci ze wskazaniem przepływu danych kart",
        ),
        (
            "pcidss_security_policy",
            "Information Security Policy (PCI DSS)",
            True,
            "compliance",
            "https://www.pcisecuritystandards.org/",
            "Polityka bezpieczeństwa informacji (Req. 12)",
        ),
        (
            "pcidss_vulnerability_scan",
            "Vulnerability Scan Report",
            True,
            "compliance",
            "https://www.pcisecuritystandards.org/",
            "Raport skanowania podatności (Req. 11)",
        ),
        (
            "pcidss_pentest_report",
            "Penetration Test Report (PCI DSS)",
            True,
            "compliance",
            "https://www.pcisecuritystandards.org/",
            "Raport testów penetracyjnych (Req. 11.3)",
        ),
        (
            "pcidss_change_control",
            "Change Control Procedure",
            True,
            "compliance",
            "https://www.pcisecuritystandards.org/",
            "Procedura kontroli zmian (Req. 6.4)",
        ),
        (
            "pcidss_access_control_policy",
            "Access Control Policy (PCI DSS)",
            True,
            "compliance",
            "https://www.pcisecuritystandards.org/",
            "Polityka kontroli dostępu (Req. 7, 8)",
        ),
        (
            "pcidss_roc",
            "Report on Compliance (RoC)",
            True,
            "compliance",
            "https://www.pcisecuritystandards.org/",
            "Raport zgodności PCI DSS (QSA assessment)",
        ),
        (
            "pcidss_saq",
            "Self-Assessment Questionnaire (SAQ)",
            True,
            "compliance",
            "https://www.pcisecuritystandards.org/",
            "Kwestionariusz samooceny",
        ),
    ],
    # ── SOC 2 ────────────────────────────────────────────────────────────
    "SOC 2": [
        (
            "soc2_security_policy",
            "Security Policy (SOC 2 TSC)",
            True,
            "compliance",
            "https://www.aicpa.org/interestareas/frc/assuranceadvisoryservices/socforserviceorganizations.html",
            "Polityka bezpieczeństwa wg. Trust Service Criteria",
        ),
        (
            "soc2_availability_policy",
            "Availability Policy",
            True,
            "compliance",
            "https://www.aicpa.org/interestareas/frc/assuranceadvisoryservices/socforserviceorganizations.html",
            "Polityka dostępności",
        ),
        (
            "soc2_processing_integrity",
            "Processing Integrity Policy",
            False,
            "compliance",
            "https://www.aicpa.org/interestareas/frc/assuranceadvisoryservices/socforserviceorganizations.html",
            "Polityka integralności przetwarzania",
        ),
        (
            "soc2_confidentiality_policy",
            "Confidentiality Policy",
            True,
            "compliance",
            "https://www.aicpa.org/interestareas/frc/assuranceadvisoryservices/socforserviceorganizations.html",
            "Polityka poufności",
        ),
        (
            "soc2_control_description",
            "System Description & Controls",
            True,
            "compliance",
            "https://www.aicpa.org/interestareas/frc/assuranceadvisoryservices/socforserviceorganizations.html",
            "Opis systemu i kontroli (sekcja 3 raportu SOC 2)",
        ),
        (
            "soc2_risk_assessment",
            "Risk Assessment (SOC 2)",
            True,
            "compliance",
            "https://www.aicpa.org/interestareas/frc/assuranceadvisoryservices/socforserviceorganizations.html",
            "Ocena ryzyka per TSC",
        ),
        (
            "soc2_vendor_mgmt",
            "Vendor Management Policy",
            True,
            "compliance",
            "https://www.aicpa.org/interestareas/frc/assuranceadvisoryservices/socforserviceorganizations.html",
            "Polityka zarządzania dostawcami",
        ),
    ],
    # ── COBIT 2019 ────────────────────────────────────────────────────────
    "COBIT 2019": [
        (
            "cobit_it_strategy",
            "IT Strategy Document (COBIT)",
            True,
            "governance",
            "https://www.isaca.org/resources/cobit",
            "Strategia IT wg. COBIT 2019",
        ),
        (
            "cobit_governance_framework",
            "IT Governance Framework Description",
            True,
            "governance",
            "https://www.isaca.org/resources/cobit",
            "Opis frameworku ładu IT",
        ),
        (
            "cobit_process_desc",
            "Governance/Management Process Descriptions",
            True,
            "governance",
            "https://www.isaca.org/resources/cobit",
            "Opisy procesów zarządczych i menedżerskich",
        ),
        (
            "cobit_maturity_assessment",
            "Process Capability/Maturity Assessment",
            False,
            "governance",
            "https://www.isaca.org/resources/cobit",
            "Ocena dojrzałości procesów IT",
        ),
        (
            "cobit_audit_report",
            "IT Audit Report (COBIT)",
            False,
            "governance",
            "https://www.isaca.org/resources/cobit",
            "Raport audytu IT wg. COBIT",
        ),
        (
            "cobit_risk_profile",
            "IT Risk Profile",
            True,
            "governance",
            "https://www.isaca.org/resources/cobit",
            "Profil ryzyka IT",
        ),
    ],
}


# ---------------------------------------------------------------------------


def create_table(conn: sqlite3.Connection) -> None:
    conn.execute("""
        CREATE TABLE IF NOT EXISTS standards_catalog (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            standard_code TEXT NOT NULL,
            doc_type_id   TEXT NOT NULL UNIQUE,
            doc_title     TEXT NOT NULL,
            is_required   INTEGER NOT NULL DEFAULT 1,
            category      TEXT,
            source_url    TEXT,
            notes         TEXT,
            created_at    TEXT DEFAULT (datetime('now')),
            FOREIGN KEY (standard_code) REFERENCES standards(standard_code)
        )
    """)
    conn.execute("CREATE INDEX IF NOT EXISTS idx_sc_standard ON standards_catalog(standard_code)")
    conn.execute("CREATE INDEX IF NOT EXISTS idx_sc_category ON standards_catalog(category)")
    conn.commit()


def count_existing(conn: sqlite3.Connection) -> int:
    return conn.execute("SELECT COUNT(*) FROM standards_catalog").fetchone()[0]


def load_catalog(conn: sqlite3.Connection, replace: bool = False) -> dict[str, int]:
    if replace:
        conn.execute("DELETE FROM standards_catalog")
        conn.commit()

    stats: dict[str, int] = {}
    for standard_code, entries in CATALOG.items():
        inserted = 0
        for doc_type_id, doc_title, is_required, category, source_url, notes in entries:
            try:
                conn.execute(
                    """INSERT OR IGNORE INTO standards_catalog
                       (standard_code, doc_type_id, doc_title, is_required, category, source_url, notes)
                       VALUES (?, ?, ?, ?, ?, ?, ?)""",
                    (
                        standard_code,
                        doc_type_id,
                        doc_title,
                        int(is_required),
                        category,
                        source_url,
                        notes,
                    ),
                )
                inserted += 1
            except sqlite3.IntegrityError as e:
                print(f"  SKIP {doc_type_id}: {e}")
        stats[standard_code] = inserted
    conn.commit()
    return stats


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--db", default=DB_DEFAULT, help="Path to SQLite DB")
    ap.add_argument("--replace", action="store_true", help="Delete and re-insert all rows")
    ap.add_argument("--stats", action="store_true", help="Print stats only, don't insert")
    args = ap.parse_args()

    conn = sqlite3.connect(args.db)
    create_table(conn)

    if args.stats:
        n = count_existing(conn)
        print(f"Catalog entries in DB: {n}")
        rows = conn.execute(
            "SELECT standard_code, COUNT(*) FROM standards_catalog GROUP BY standard_code ORDER BY standard_code"
        ).fetchall()
        for code, cnt in rows:
            print(f"  {code}: {cnt}")
        conn.close()
        return

    stats = load_catalog(conn, replace=args.replace)
    print("=== Standards Catalog loaded ===")
    total = 0
    for code, n in sorted(stats.items()):
        print(f"  {code:40s} +{n}")
        total += n
    print(f"\nTotal inserted: {total} catalog entries across {len(stats)} standards")

    # Summary: which standards from DB have no catalog entries yet?
    missing = conn.execute("""
        SELECT s.standard_code FROM standards s
        WHERE NOT EXISTS (SELECT 1 FROM standards_catalog c WHERE c.standard_code = s.standard_code)
        ORDER BY s.standard_code
    """).fetchall()
    if missing:
        print(f"\nWARN: Standards with no catalog entries: {[r[0] for r in missing]}")
    else:
        print(f"\nAll {len(CATALOG)} standards covered.")
    conn.close()


if __name__ == "__main__":
    main()
